version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
  web:
    build: .
    container_name: fastapi_app
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    env_file:
      - .env-non-dev
    depends_on:
      - db

volumes:
  postgres_data:
